version: '3'
services:
    web:
        build: .
        ports: 
            - 1337:1337
        depends_on: 
            - db
        environment: 
            - NODE_ENV=dev
        command: npm run start
        volumes: 
            - ./build:./build
        restart: always
    db: 
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        restart: unless-stopped
        volumes: 
            - ./dump:/dump


        