version: '3'
services:
    web:
        build: .
        ports: 
            - 1337:1337
        depends_on: 
            - db
        environment: 
            - NODE_ENV=dev
        command: npm run develop
        volumes: 
            - ./build:/usr/local/app/build
            - ./public:/user/local/app/public
        restart: always
    db: 
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        volumes: 
            - ./dump:/dump


        